name: Jonathan Como
paginate: 5 # pagination basted on number of posts
pygments: true
safe: true
lsi: false
source: .
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss']
